/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.bugsplat.java-library-conventions")
}

dependencies {
    implementation("org.apache.httpcomponents:httpclient:4.5.14")
    implementation("org.apache.httpcomponents:httpmime:4.5.14")
    implementation("org.json:json:20230227")
}
