/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bugsplat.app;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class MyJavaCrasherConsoleTest {
    @Test void testGetMessage() {
        MyJavaCrasherConsole.main(new String[]{});
    }
}
