/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.bugsplat.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":bugsplat"))
}

application {
    // Define the main class for the application.
    mainClass.set("com.bugsplat.app.MyJavaCrasherConsole")
}
