/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bugsplat;

class TestTest {
    @org.junit.jupiter.api.Test
    void testConstructor() {
        //Test.test();
    }
}
